---
title: Homey Point Application
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    values:
      author_profile: true
  uploads:
    title: Uploads
    output: true
sidebar:
  nav: docs
  classes: wide
theme: jekyll-theme-slate
