---
title: Homey Point Application
timezone: UTC
theme: jekyll-theme-slate
description: An app for adding the minute point to the homey
show_downloads: true
github:
  zip_url: https://apps.athom.com/app/com.ketra.point
  another_url: https://apps.athom.com/app/com.ketra.point
